# Generated by Django 3.0.8 on 2020-07-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinstruments',
            name='kartaPomiarow',
            field=models.FileField(null=True, upload_to='kartyPomiarow/'),
        ),
    ]
