# Generated by Django 3.0.8 on 2020-07-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_groupinstruments_kartapomiarow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupinstruments',
            old_name='kartaPomiarow',
            new_name='kartaPomiarowPlik',
        ),
        migrations.AddField(
            model_name='groupinstruments',
            name='kartaPomiarowNazwa',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
