# Generated by Django 3.0.8 on 2020-08-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200807_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinstruments',
            name='karta',
        ),
        migrations.AddField(
            model_name='grupakartapomiarow',
            name='idGrupa',
            field=models.ManyToManyField(to='api.GroupInstruments'),
        ),
    ]
