# Generated by Django 3.0.8 on 2020-08-07 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200807_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupakartapomiarow',
            name='idGrupa',
        ),
        migrations.AddField(
            model_name='grupakartapomiarow',
            name='idGrupa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karta', to='api.GroupInstruments'),
        ),
    ]
