# Generated by Django 3.0.8 on 2020-08-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200807_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinstruments',
            name='kartaPomiarowNazwa',
        ),
        migrations.RemoveField(
            model_name='groupinstruments',
            name='kartaPomiarowPlik',
        ),
    ]
