# Generated by Django 3.0.8 on 2020-08-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_grupakartapomiarow_nazwa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupakartapomiarow',
            old_name='kartaPomiarow',
            new_name='link',
        ),
    ]
