# Generated by Django 3.1.2 on 2020-10-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200807_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinstruments',
            name='interwalJednostka',
            field=models.CharField(default='d', max_length=32),
        ),
        migrations.AddField(
            model_name='groupinstruments',
            name='interwalWartosc',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='groupinstruments',
            name='jednostkaNazwa',
            field=models.CharField(default='milimetr', max_length=32),
        ),
        migrations.AddField(
            model_name='groupinstruments',
            name='jednostkaSkrot',
            field=models.CharField(default='mm', max_length=32),
        ),
    ]
