# Generated by Django 3.1.2 on 2020-10-20 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_obszary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obszary',
            name='idUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obszar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Lokalizacje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=32)),
                ('idObszar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lokalizacja', to='api.obszary')),
            ],
        ),
    ]
