# Generated by Django 3.1.2 on 2020-10-20 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201020_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Przyrzady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=32)),
                ('typ', models.CharField(max_length=32)),
                ('status', models.IntegerField(default=0)),
                ('wzorzec', models.BooleanField(default=False)),
                ('idGrupa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='przyrzad', to='api.groupinstruments')),
                ('idLokalizacja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='przyrzad', to='api.lokalizacje')),
            ],
        ),
    ]
