# Generated by Django 3.1.2 on 2020-10-21 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_przyrzady'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przyrzady',
            name='idGrupa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='przyrzad', to='api.groupinstruments'),
        ),
        migrations.AlterField(
            model_name='przyrzady',
            name='idLokalizacja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='przyrzad', to='api.lokalizacje'),
        ),
        migrations.CreateModel(
            name='SprawdzeniaPlanowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPlanowa', models.DateField()),
                ('idPrzyrzad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprawdzenia_planowe', to='api.przyrzady')),
            ],
        ),
    ]
