# Generated by Django 3.1.2 on 2020-10-27 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201021_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statusy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='lokalizacje',
            name='idObszar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lokalizacja', to='api.obszary'),
        ),
        migrations.AlterField(
            model_name='sprawdzeniaplanowe',
            name='idPrzyrzad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprawdzeniaPlanowe', to='api.przyrzady'),
        ),
    ]
