# Generated by Django 3.1.2 on 2020-10-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201027_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przyrzady',
            name='aktStatus',
            field=models.IntegerField(default=0),
        ),
    ]
