# Generated by Django 3.1.2 on 2020-11-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20201031_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='JednostkiBadane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=32)),
                ('skrot', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='JednostkiInterwal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=32)),
                ('skrot', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupinstruments',
            name='interwalJednostka',
        ),
        migrations.RemoveField(
            model_name='groupinstruments',
            name='interwalWartosc',
        ),
        migrations.RemoveField(
            model_name='groupinstruments',
            name='jednostkaNazwa',
        ),
        migrations.RemoveField(
            model_name='groupinstruments',
            name='jednostkaSkrot',
        ),
    ]
