# Generated by Django 3.1.2 on 2020-11-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20201101_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='przyrzady',
            name='nrFabryczny',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='przyrzady',
            name='zakres',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='przyrzady',
            name='typ',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
