# Generated by Django 3.1.2 on 2020-11-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20201103_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiadectwoSprawdzenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrSwiadectwa', models.CharField(max_length=32)),
                ('przedmiot', models.CharField(max_length=1000)),
                ('metoda', models.CharField(max_length=100, null=True)),
                ('uzyteWzorce', models.CharField(max_length=255, null=True)),
                ('warunkiSrodowiskowe', models.CharField(max_length=255, null=True)),
                ('dataSprawdzenia', models.DateField()),
                ('dataNastepnejKontroli', models.DateField()),
                ('wynikSprawdzenia', models.BooleanField(default=False)),
                ('uwagi', models.CharField(max_length=1000, null=True)),
                ('sprawdzajacy', models.CharField(max_length=255)),
                ('przedmiotId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swiadectwa', to='api.przyrzady')),
            ],
        ),
        migrations.CreateModel(
            name='SwiadectwoSprawdzeniaSzablon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzyteWzorce', models.CharField(max_length=255, null=True)),
                ('warunkiSrodowiskowe', models.CharField(max_length=255, null=True)),
                ('grupaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wzor', to='api.groupinstruments')),
            ],
        ),
        migrations.CreateModel(
            name='SwiadectwoSprawdzeniaPlik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.FileField(upload_to='swiadectwaSprawdzenia/')),
                ('nazwa', models.CharField(max_length=50, null=True)),
                ('idSwiadectwoSprawdzenia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plik', to='api.swiadectwosprawdzenia')),
            ],
        ),
    ]
