# Generated by Django 3.1.2 on 2020-11-12 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_swiadectwosprawdzenia_swiadectwosprawdzeniaplik_swiadectwosprawdzeniaszablon'),
    ]

    operations = [
        migrations.AddField(
            model_name='swiadectwosprawdzenia',
            name='sprawdzenieZewnetrzne',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='przyrzady',
            name='idLokalizacja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='przyrzady', to='api.lokalizacje'),
        ),
    ]
