# Generated by Django 3.1.2 on 2020-11-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20201112_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='przyrzady',
            name='nr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='swiadectwosprawdzeniaplik',
            name='link',
            field=models.FileField(upload_to='swiadectwa-sprawdzenia/'),
        ),
    ]
