# Generated by Django 3.1.2 on 2020-11-24 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20201115_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatyPrzyrzadu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataOstatniegoSprawdzenia', models.DateField()),
                ('dataNastepnegoSprawdzenia', models.DateField()),
                ('nrSwiadectwa', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='przyrzady',
            name='daty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datyprzyrzadu'),
        ),
    ]
