# Generated by Django 3.1.2 on 2020-11-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20201124_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='swiadectwosprawdzenia',
            name='dataOstatniejKontroli',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='swiadectwosprawdzenia',
            name='nrAktualnegoSwiadectwa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='swiadectwosprawdzenia',
            name='dataNastepnejKontroli',
            field=models.DateField(null=True),
        ),
    ]
