# Generated by Django 3.1.2 on 2020-11-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_swiadectwosprawdzenia_nraktualnegoswiadectwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiadectwosprawdzenia',
            name='dataNastepnejKontroli',
            field=models.DateField(),
        ),
    ]
