# Generated by Django 3.1.2 on 2020-11-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20201124_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swiadectwosprawdzenia',
            name='dataOstatniejKontroli',
        ),
    ]
