# Generated by Django 3.1.2 on 2020-11-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_swiadectwosprawdzenia_dataostatniejkontroli'),
    ]

    operations = [
        migrations.AddField(
            model_name='przyrzady',
            name='dataNastepnejKontroli',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='przyrzady',
            name='dataOstatniejKontroli',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='przyrzady',
            name='nrAktualnegoSwiadectwa',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
